### ISSUE TITLE
Unable to compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by mclements** [HackerDom/cim#1]
This is very nice work updating the old `GNU cim` source.

However, I was not able to compile using gcc 7.4.0 on Ubuntu 18.04. There are many warnings such as:

`cim.h:363:33: warning: declaration does not declare anything:  struct __s_simplenamepar;`

And errors for accessing names in `_simplenamepar` that are used in other structs, e.g.

`getav.c:51:12: error: ‘__aritnamepar {aka struct <anonymous>}’ has no member named ‘namekind’`
`   switch (p->namekind)`

This seems to relate to your refactored code using `_simplenamepar`, where the anonymous unions in the later structs do not have access to names from `_simplenamepar`. 

Could this be explained by the choice of compiler and C standard?

Sincerely, Mark.

**Comment by alexanderkjeldaas** [comment]
I've compiled successfully on OS X using a few changes.  See 

https://github.com/alexanderkjeldaas/cim

This particular issue requires:
```
CFLAGS="-fms-extensions -Wno-microsoft-anon-tag" ./configure
```

See the https://github.com/alexanderkjeldaas/cim/blob/master/BUILD.md
